{% set name = "isabelle-client" %}
{% set version = "1.0.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/isabelle_client-{{ version }}.tar.gz
  sha256: b9db2c1b4f22eee42067942b7fa5c594cd3cede8259b0d3f4d882059ee93006d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - pydantic

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  source_files:
    - src
  commands:
    - pip check
    - pytest --doctest-modules

about:
  home: https://github.com/inpefess/isabelle-client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A client for Isabelle server (https://isabelle.in.tum.de)
  description: |
    isabelle-client is a TCP client for Isabelle server. For more information
    about the server see part 4 of the Isabelle system manual:
    https://isabelle.in.tum.de/dist/Isabelle2025/doc/system.pdf#page=52
  doc_url: https://isabelle-client.readthedocs.io/
  dev_url: https://github.com/inpefess/isabelle-client

extra:
  recipe-maintainers:
    - inpefess
