{% set name = "isabelle-client" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12d96bd6b7610a85f7b7ccbdac40ebf9005e6b5cce8647b9db17e402751254df

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.6

test:
  imports:
    - isabelle_client
  requires:
    - pip
    - pytest
  source_files:
    - isabelle_client
  commands:
    - pip check
    - pytest --override-ini doctest_optionflags=NORMALIZE_WHITESPACE --doctest-modules isabelle_client

about:
  home: https://github.com/inpefess/isabelle-client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A client for Isabelle server (https://isabelle.in.tum.de)
  description: |
    isabelle-client is a TCP client for Isabelle server. For more information
    about the server see part 4 of the Isabelle system manual:
    https://isabelle.in.tum.de/dist/Isabelle2021-1/doc/system.pdf
  doc_url: https://isabelle-client.readthedocs.io/
  dev_url: https://github.com/inpefess/isabelle-client

extra:
  recipe-maintainers:
    - inpefess
