{% set name = "isabelle-client" %}
{% set version = "0.5.5" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/isabelle_client-{{ version }}.tar.gz
  sha256: 7361b6b287fd8dc66e85b69695e25f0c3c86796166ed42163a870503fa949292

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - isabelle_client
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  source_files:
    - isabelle_client
  commands:
    - pip check
    - pytest --override-ini doctest_optionflags=ELLIPSIS --doctest-modules isabelle_client

about:
  home: https://github.com/inpefess/isabelle-client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A client for Isabelle server (https://isabelle.in.tum.de)
  description: |
    isabelle-client is a TCP client for Isabelle server. For more information
    about the server see part 4 of the Isabelle system manual:
    https://isabelle.in.tum.de/dist/Isabelle2021-1/doc/system.pdf
  doc_url: https://isabelle-client.readthedocs.io/
  dev_url: https://github.com/inpefess/isabelle-client

extra:
  recipe-maintainers:
    - inpefess
